[project]
name = "gui-kanken-quiz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "jaconv>=0.4.1",
    "openai>=2.15.0",
    "pandas>=3.0.0",
    "pyside6>=6.10.1",
]
